language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid
      - cabal-install

before-script:
  - 'cabal update'
  - 'cabal install shellcheck'

script:
  - bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh .functions/*'

matrix:
  fast_finish: true
