[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer, the value of this option is a string.
  colorscheme = "molokai"
  colorscheme_bg = "dark"

  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors, the type of the value is boolean, true or false.
  enable_guicolors = true

  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "nil"
  statusline_iseparator = "bar"
  buffer_index_type = 4

  # Display file type icon on the tabline, If you do not have nerd fonts
  # installed, please change the value to false
  enable_tabline_filetype_icon = true
  # Display current mode text on statusline, by default It is disabled,
  # only color will be changed when switch modes.
  enable_statusline_mode = false

  # disable auto update
  automatic_update = false

  # find nearest dir for project manager
  project_rooter_outermost = false

  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"  # "cycle" is another opt

[[layers]]
  name = "colorscheme"

# [[layers]]
#   name = "checkers"

[[layers]]
  name = "cscope"

[[layers]]
  name = "denite"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "tags"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "format"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rust-analyzer"]

  enabled_clients = ['vimls', 'clangd']

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30
  # enable = false

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#elixir"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#pact"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#solidity"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#tmux"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#WebAssembly"

# [[custom_plugins]]
#   repo = "lilydjwg/colorizer"
#   merged = false
